version: 2

jobs:
  build_and_test_python36:
    docker:
      - image: circleci/python:3.6
      - image: rabbitmq:3
      - image: mongo:3.4

    working_directory: ~/repo

    environment:
      VIRTUALENV_DIR: "~/virtualenv"
      # Don't install various StackStorm dependencies which are already
      # installed by CI again in the various check scripts
      ST2_INSTALL_DEPS: "0"

    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-py36-{{ checksum "requirements.txt" }}
      - run:
          name: Download dependencies
          # NOTE: We don't want to use default "-e" option because this means
          # step will fail immediately on one of the commands failures and we
          # can't intercept the error and cause non-fatal exit in case pack
          # doesn't declare support for Python 3
          shell: /bin/bash
          command: |
            git clone -b master git@github.com:StackStorm-Exchange/ci.git ~/ci
            ~/ci/.circle/dependencies ; ~/ci/.circle/exit_on_py3_checks $?
      - run:
          name: Run tests (Python 3.6)
          # NOTE: We don't want to use default "-e" option because this means
          # step will fail immediately on one of the commands failures and we
          # can't intercept the error and cause non-fatal exit in case pack
          # doesn't declare support for Python 3
          shell: /bin/bash
          command: ~/ci/.circle/test ; ~/ci/.circle/exit_on_py3_checks $?
      - save_cache:
          key: v1-dependency-cache-py36-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
            - ~/.apt-cache

workflows:
  version: 2
  build_test_deploy_on_push:
    jobs:
      - build_and_test_python36
  build_test_weekly:
    jobs:
      - build_and_test_python36
    # Workflow which runs nightly - note we don't perform deploy job on nightly
    # build
    triggers:
      # Run nightly build for the pack
      - schedule:
          # NOTE: We run it at 1 am UTC on every Saturday
          cron: "0 1 * * 6"
          filters:
            branches:
              only:
                - master
