---
name: test_cron
pack: errors
description: "Testing cron sensor"
enabled: true

trigger:
  type: "core.st2.CronTimer"
  # http://apscheduler.readthedocs.io/en/3.0/modules/triggers/cron.html#api
  parameters:
      timezone: "UTC"
      day_of_week: "*"
      hour: 22
      minute: 30
      second: 0

action:
  ref: "errors.test_cron_sensor"